version: '3.9'
services:
  postgres:
    image: postgres:13.4
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    ports:
        - 5432:5432/tcp